require 'spec_helper'

describe Cdx do
  it "should provide a collection of fields" do
    expect(Cdx.core_fields.map(&:scoped_name).sort).to eq([
      "device.model",
      "device.name",
      "device.serial_number",
      "device.uuid",
      "encounter.end_time",
      "encounter.id",
      "encounter.start_time",
      "encounter.uuid",
      "institution.name",
      "institution.uuid",
      "location.admin_levels",
      "location.id",
      "location.lat",
      "location.lng",
      "location.parents",
      "patient.gender",
      "patient.id",
      "patient.name",
      "sample.collection_date",
      "sample.id",
      "sample.type",
      "sample.uuid",
      "site.name",
      "site.uuid",
      "test.assays.condition",
      "test.assays.name",
      "test.assays.quantitative_result",
      "test.assays.result",
      "test.end_time",
      "test.error_code",
      "test.error_description",
      "test.id",
      "test.name",
      "test.patient_age",
      "test.reported_time",
      "test.site_user",
      "test.start_time",
      "test.status",
      "test.type",
      "test.updated_time",
      "test.uuid"].sort)
  end
end
